name: terraform-module-setup
on: [push]   

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: roxanapopa/docker-git-workflows:v0.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Generate TF Plan
        run: |
          cd fixtures
          terraform init
          terraform plan --out tfplan.binary
          pwd
          ls -lah
          terraform show -json tfplan.binary > plan_output.json
      - name: Run Pytest
        run: pytest tests/

      # - name: Init
      #   run: terraform init
      # - name: Plan
      #   run: terraform plan
      # - name: Apply
      #   run: terraform apply -auto-approve
      