name: terraform-module-setup
on: [push]   

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: roxanapopa/docker-git-workflows:v0.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate TF Plan
        run: |
          cd fixtures
          terraform init
          terraform plan --out tfplan.binary
          terraform show -json tfplan.binary > plan_output.json
      - name: Run Pytest
        run: pytest tests/

      # - name: Init
      #   run: terraform init
      # - name: Plan
      #   run: terraform plan
      # - name: Apply
      #   run: terraform apply -auto-approve
      